easy_admin:
    entities:
        # List the entity class name you want to manage
        User:
          class: App\Entity\User
          new:
            title: 'Add User'
            fields:
            - { property: 'username', type: 'text', label: 'Name' }
            - { property: 'email', type: 'email', label: 'E-Mail' }
            - { property: 'plainPassword', type: 'password', label: 'Password' }
          edit:
            title: 'Edit User'
        BlogPost:
          class: App\Entity\BlogPost

    design:
      brand_color: '#333333'